baseURL = '/'
languageCode = 'en-us'
title = 'Hugo Boss Demo'

[security.exec]
allow = ['^(dart-)?sass$', '^go$', '^git$', '^npx$', '^postcss$', '^asciidoctor$']

[markup.asciidocExt]
backend = 'html5'
safeMode = 'unsafe'
